CREATE TABLE IDS_PIN (
  ID                INT(11) PRIMARY KEY AUTO_INCREMENT,
  CONN_ID           INT(11),
  PIN_CODE          VARCHAR(20),
  DIRECTION         VARCHAR(32),
  TYPE              VARCHAR(64),
  CODE              VARCHAR(64),
  SIGNAL_CONTENT    VARCHAR(128),
  LOAD_CHARACTER    VARCHAR(64),
  LOAD_VOLTAGE      VARCHAR(64),
  LOAD_CURRENT      VARCHAR(64),
  TWIN_TWIST        VARCHAR(64),
  SHIELD            VARCHAR(64),
  SHIELD_GROUND     VARCHAR(64),
  COLOR             VARCHAR(64),
  LINENUMBER        VARCHAR(64),
  REMARK            VARCHAR(128),
  IS_IGNORE         INT(1),
  FILE_LIST_ID      VARCHAR(20) NOT NULL,
  MAIN_ATTRID       VARCHAR(20),
  PIN_LEVEL         INT(1),
  LASTREPLACEDPINID VARCHAR(20),
  FROM_ATTRID       VARCHAR(20),
  TO_ATTRID         VARCHAR(20),
  PRIO_LEVEL        INT(1),
  PRIMARY_ATTR      VARCHAR(255)
);

CREATE TABLE IDS_CONNECTOR (
  ID   INT(11) PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(128)
);